MVC-POO/MVC-POO/Models/EmpleadosModelView.cs
using MVC_POO.Entidades;

namespace MVC_POO.Models
{
    public class EmpleadosModelView
    {
        public List<Empleado> Empleados { get; set; }
        public List<Contratado> Contratados { get; set; }
    }
}

MVC-POO/MVC-POO/Models/ErrorViewModel.cs
namespace MVC_POO.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-POO/MVC-POO/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_POO.Entidades;
using MVC_POO.Logica;
using MVC_POO.Models;

namespace MVC_POO.Controllers
{
    public class EmpleadosController : Controller
    {
        public IEmpleadoLogica _empleadoService;
        public IContractorsLogica _contractorService;

        public EmpleadosController(IEmpleadoLogica empleadoService,IContractorsLogica contractorService)
        {
            _empleadoService = empleadoService;
            _contractorService = contractorService;
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = _empleadoService.ObtenerTodos();
            List<Contratado> contratados = _contractorService.ObtenerTodos();


            var total = LiquidadorSueldos<Empleado>.CalcularSueldosTotalEmpleado(empleados);
            total += LiquidadorSueldos<Contratado>.CalcularSueldosTotalEmpleado(contratados);

            EmpleadosModelView emv = new EmpleadosModelView()
            {
                Empleados = empleados,
                Contratados = contratados
            };

            ViewBag.SueldoALiquidar = total;
            return View(emv);
        }

        [HttpGet]
        public IActionResult LiquidarSueldos() {
            return View();
        }

        [HttpPost]
        public IActionResult LiquidarSueldosPost()
        {
            return View();
        }


        [HttpGet]
        public IActionResult AgregarEmpleadoPasante() {
            return View();
        }



        [HttpPost]
        public IActionResult AgregarEmpleadoPasantePost(Pasante pasante)
        {

            _empleadoService.Agregar(pasante);
            return RedirectToAction("Index");
        }
    }
}

MVC-POO/MVC-POO/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_POO.Models;
using System.Diagnostics;

namespace MVC_POO.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC-POO/MVC-POO/Views/Empleados/AgregarEmpleadoPasante.cshtml
@model MVC_POO.Entidades.Pasante


<h1>Agregar empleados pasante</h1>
<h4>Pasante</h4>

<hr />
<form method="post" asp-action="AgregarEmpleadoPasantePost" asp-controller="Empleados">
    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control"/>
    </div>

    <div class="form-group">
        <label asp-for="SueldoBase"></label>
        <input asp-for="SueldoBase" class="form-control" />
    </div>

    <input type="submit" value="Enviar" class="btn btn-primary"/>
        
</form>

MVC-POO/MVC-POO/Views/Empleados/Index.cshtml
@model MVC_POO.Models.EmpleadosModelView;

<h1>Empleados</h1>


<a asp-action="AgregarEmpleadoPasante">Crear nuevo</a>

<table>
    <thead>
        <th>Nombre Completo</th>
        
        <th>SueldoBase</th>

         <th>Antiguedad</th>

         <th>Hs Extras</th>
    </thead>
    <tbody>
        @foreach(var empleado in Model.Empleados)
        {
            <!--Mostramos los atributos de cada empleado en la lista-->
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => empleado.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => empleado.SueldoBase)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => empleado.Antiguedad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => empleado.HorasExtras)
                </td>
            </tr>
        }
    </tbody>
</table>

<h1>Contratados</h1>

<table>

    <thead>
        <th>Valor x Hora</th>

        <th>Horas trabajadas</th>
    </thead>
    <tbody>
        @foreach (var empleado in Model.Contratados)
        {
            <!--Mostramos los atributos de cada empleado en la lista-->
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => empleado.ValorHora)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => empleado.HorasTrabajadas)
                </td>
            </tr>
        }
    </tbody>
</table>

<h2>Sueldo a liquidar: @ViewBag.SueldoALiquidar</h2>