MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Models/ErrorViewModel.cs
namespace MVC_ModeloParcialMiercoles11Mayo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Models/VentaViewModel.cs
using MVC_ModeloParcialMiercoles11Mayo.Entidades;

namespace MVC_ModeloParcialMiercoles11Mayo.Models
{
    public class VentaViewModel
    {
        public int Id { get; set; }
        public String Cliente { get; set; }
        public int CantidadVendida { get; set; }
        public int PrecioUnitario { get; set; }
        public int TotalVenta { get; set; }


        public static VentaViewModel ParseToVentaViewModel(Venta venta)
        {
            VentaViewModel obj =  new VentaViewModel
            {
                Id = venta.Id,
                Cliente = venta.Cliente,
                CantidadVendida = venta.CantidadVendida,
                PrecioUnitario = venta.PrecioUnitario
            };

            obj.TotalVenta = obj.CantidadVendida * venta.PrecioUnitario;
            return obj;
        }

        public static List<VentaViewModel> FromVentaToVentaViewModel(List<Venta> ventas)
        {
            return ventas.Select(x => ParseToVentaViewModel(x))
                    .ToList();
        }

    }
}

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Controllers/PresentacionController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ModeloParcialMiercoles11Mayo.Models;
using System.Diagnostics;

namespace MVC_ModeloParcialMiercoles11Mayo.Controllers
{
    public class PresentacionController : Controller
    {
        private readonly ILogger<PresentacionController> _logger;

        public PresentacionController(ILogger<PresentacionController> logger)
        {
            _logger = logger;
        }

        public IActionResult Bienvenido()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Controllers/VentaController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_ModeloParcialMiercoles11Mayo.Entidades;
using MVC_ModeloParcialMiercoles11Mayo.Logica;
using MVC_ModeloParcialMiercoles11Mayo.Models;

namespace MVC_ModeloParcialMiercoles11Mayo.Controllers
{
    public class VentaController : Controller
    {
        private IVentaService _ventaService;

        public VentaController(IVentaService ventaService)
        {
            _ventaService = ventaService;
        }

        public IActionResult RegistrarVenta()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RegistrarVentaPOST(Venta venta)
        {
            if (!ModelState.IsValid) {
                return View("RegistrarVenta", venta);
            }

            _ventaService.Guardar(venta);
            return RedirectToAction("Resultados");
        }


        public IActionResult Resultados()
        {
            List<Venta> ventas = _ventaService.ObtenerVentas();
            List<VentaViewModel> _ventasVM = VentaViewModel.FromVentaToVentaViewModel(ventas);
            return View(_ventasVM);
        }
    }
}

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Views/Presentacion/Bienvenido.cshtml
﻿
<h1 class="fs-1 text-center fw-light">Bienvenido al sitio de evaluacion</h1>
<div class="d-flex flex-column align-items-center gap-3 mt-4">
    <a asp-controller="Venta" asp-action="RegistrarVenta" class="w-50 fs-5 fw-semibold btn btn-success text-white text-decoration-none">Registrar Venta</a>
    <a asp-controller="Venta" asp-action="Resultados" class="w-50 fs-5 fw-semibold btn btn-success text-white text-decoration-none">Resultados</a>
</div>

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Evaluacion PW3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MVC_PracticaParcialUno.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class=" bg-success text-white border-bottom box-shadow mb-3 py-3">
            <a asp-controller="Presentacion" asp-action="Bienvenido" class="text-center fs-4 d-block text-white text-decoration-none d-block">UNLAM - Practica Parcial de Programacion Web III</a>
        </nav>
    </header>
    <div class="container" style="height:80vh">
        <main role="main" class="py-4">
            @RenderBody(){
            <h2>dqwdwq</h2>
            }
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container d-flex flex-column align-items-center pt-4 pb-0">
            <p>Alan Aruquipa</p>
            <p>45323639</p>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Views/Venta/RegistrarVenta.cshtml
@model MVC_ModeloParcialMiercoles11Mayo.Entidades.Venta;

<div class="d-flex justify-content-center">

    <form asp-controller="Venta" asp-action="RegistrarVentaPOST" class="w-50 p-4" method="post">
        <fieldset class="border p-2">
            <legend class="float-none w-auto fs-5 fw-semibold text-success">Ventas</legend>

            <div class="d-flex flex-column gap-2">
                <div>
                    <label>Cliente: </label>
                    <input type="text" asp-for="Cliente"/>
                    <span class="text-danger" asp-validation-for="Cliente"></span>
                </div>
                
                <div>
                    <label>Cantidad Vendida: </label>
                    <input type="text" asp-for="CantidadVendida"/>
                    <span class="text-danger" asp-validation-for="CantidadVendida"></span>
                </div>

                <div>
                    <label>Precio Unitario $: </label>
                    <input type="text" asp-for="PrecioUnitario"/>
                    <span class="text-danger" asp-validation-for="PrecioUnitario"></span>
                </div>
            </div>

            <button type="submit" class="btn btn-md btn-success mt-4 mx-auto">Guardar</button>
        </fieldset>    
    </form>

</div>

MVC-ModeloParcialMiercoles11Mayo/MVC-ModeloParcialMiercoles11Mayo/Views/Venta/Resultados.cshtml
@model List<VentaViewModel>
<h1 class="fs-2">Resultados</h1>

<div class="d-flex justify-content-center mt-4">
    <table class="table table-striped">
        <thead class="bg-success text-white text-center fw-light">
            <tr class="fw-light">
                <th>#IdVenta</th>
                <th>Cliente</th>
                <th>Cantidad Vendida</th>
                <th>Precio Unitario ($)</th>
                <th>Total Venta</th>
            </tr>
        </thead>
        <tbody class="text-center">
            @foreach(VentaViewModel venta in Model)
            {
                <tr>
                    <td>@venta.Id</td>
                    <td>@venta.Cliente</td>
                    <td>@venta.CantidadVendida</td>
                    <td>@venta.PrecioUnitario</td>
                    <td>$@venta.TotalVenta</td>
                </tr>
            }

        </tbody>

    </table>

</div>