RelacionesEntityFramework/RelacionesEntityFramework/Models/ErrorViewModel.cs
namespace RelacionesEntityFramework.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RelacionesEntityFramework/RelacionesEntityFramework/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using RelacionesEntityFramework.Models;
using System.Diagnostics;

namespace RelacionesEntityFramework.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RelacionesEntityFramework/RelacionesEntityFramework/Controllers/JugadorController.cs
using Microsoft.AspNetCore.Mvc;
using RelacionesEntityFramework.Data.Entidades;
using RelacionesEntityFramework.Logica;

namespace RelacionesEntityFramework.Controllers
{
    public class JugadorController : Controller
    {
        private readonly ISeleccionLogica _seleccionLogica;
        private readonly IJugadorLogica _jugadorLogica;
        public JugadorController(ISeleccionLogica seleccionLogica, IJugadorLogica jugadorLogica)
        {
            this._seleccionLogica = seleccionLogica;
            this._jugadorLogica = jugadorLogica;
        }


        public async Task<IActionResult> Index()
        {
            var jugadores = await _jugadorLogica.ObtenerTodosJugadores();
            return View(jugadores);
        }

        public async Task<IActionResult> VerJugadorPorSeleccion(int idSeleccion)
        {
            var jugadores = await _jugadorLogica.ObtenerTodosJugadoresPorSeleccion(idSeleccion);
            return View("Index",jugadores);
        }

        public async Task<IActionResult> Agregar() {
            ViewBag.Selecciones = await _seleccionLogica.ObtenerTodasAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Agregar(Jugador jugador)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Selecciones = await _seleccionLogica.ObtenerTodasAsync();
                return View(jugador);
            }
            await _jugadorLogica.GuardarJugador(jugador);
            return RedirectToAction("Index");
        }
    }
}

RelacionesEntityFramework/RelacionesEntityFramework/Controllers/PartidoController.cs
using Microsoft.AspNetCore.Mvc;
using RelacionesEntityFramework.Data.Entidades;
using RelacionesEntityFramework.Logica;

namespace RelacionesEntityFramework.Controllers
{
    public class PartidoController : Controller
    {
        private readonly IPartidoLogica _partidoLogica;
        private readonly ISeleccionLogica _seleccionLogica;

        public PartidoController(IPartidoLogica partidoLogica, ISeleccionLogica seleccionLogica)
        {
            _partidoLogica = partidoLogica;
            _seleccionLogica = seleccionLogica;

        }


        public async Task<IActionResult> Index()
        {
            List<Partido> _partidos = await _partidoLogica.ObtenerTodosLosPartidos();
            return View(_partidos);
        }


        public async Task <IActionResult> Agregar() {
            IEnumerable<Seleccion> _selecciones = await _seleccionLogica.ObtenerTodasAsync();
            ViewBag.Selecciones = _selecciones;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> Agregar(Partido partido) {
            if (!ModelState.IsValid)
            {
                IEnumerable<Seleccion> _selecciones = await _seleccionLogica.ObtenerTodasAsync();
                ViewBag.Selecciones = _selecciones;
                return View(partido);
            }
            await _partidoLogica.AgregarPartidoNuevo(partido);
            return RedirectToAction("Index");
        }
    }
}

RelacionesEntityFramework/RelacionesEntityFramework/Controllers/SeleccionController.cs
using Microsoft.AspNetCore.Mvc;
using RelacionesEntityFramework.Data.Entidades;
using RelacionesEntityFramework.Logica;

namespace RelacionesEntityFramework.Controllers
{
    public class SeleccionController : Controller
    {
        private readonly ISeleccionLogica _seleccionLogica;
        private readonly IJugadorLogica _jugadorLogica;
        public SeleccionController(ISeleccionLogica seleccionLogica, IJugadorLogica jugadorLogica) { 
            this._seleccionLogica = seleccionLogica;
            this._jugadorLogica = jugadorLogica;
        }

        public async Task<IActionResult> Index()
        {
            var selecciones = await _seleccionLogica.ObtenerTodasAsync();
            return View(selecciones);
        }


        public IActionResult Agregar() {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Agregar(Seleccion seleccion) { 
            if(!ModelState.IsValid)
                return View(seleccion);

            await _seleccionLogica.AgregarAsync(seleccion);
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> IncorporarJugador(int idSeleccion) {
            ViewBag.Jugadores = await _jugadorLogica.ObtenerTodosJugadores();
            var seleccion  =await _seleccionLogica.ObtenerPorId(idSeleccion);
            ViewBag.NombreSeleccion = seleccion.Nombre;
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> IncorporarJugador(int idSeleccion, int idJugador) {
            var jugador = await _jugadorLogica.ModificarJugador(idSeleccion, idJugador);
            return View();
        }
    }
}

RelacionesEntityFramework/RelacionesEntityFramework/Views/Jugador/Agregar.cshtml
@using RelacionesEntityFramework.Data.Enum;
@model RelacionesEntityFramework.Data.Entidades.Jugador

@using (Html.BeginForm("Agregar", "Jugador", FormMethod.Post))
{
    <div>
        @Html.LabelFor(Model => Model.Nombre)
        ;
        @Html.EditorFor(Model => Model.Nombre)
        ;
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div>
        @Html.LabelFor(Model => Model.Apellido)
        ;
        @Html.EditorFor(Model => Model.Apellido)
        ;
        
        <span asp-validation-for="Apellido" class="text-danger"></span>
    </div>

    <div>
        @Html.LabelFor(Model => Model.FechaNacimiento)
        ;
        @Html.EditorFor(Model => Model.FechaNacimiento)
        ;

    </div>
    <div>
        @Html.LabelFor(Model => Model.PiernaHabil);
        @*Recorro cada valor del enumerador*@
        @foreach (var piernaItem in Enum.GetValues(typeof(Enums.PiernaHabil)))
        {
            <div>
                @Html.RadioButtonFor(Model => Model.PiernaHabil , (int)piernaItem);
                @piernaItem
            </div>
            
        }

    </div>
    <div>
        @Html.LabelFor(Model => Model.IdSeleccion)
        ;
        <!--Dibuja un drodown de las selecciones donde su valor es Id y su value el nombre de cada seleccion (similar a foreach)-->
        @Html.DropDownListFor(Model => Model.IdSeleccion, new SelectList(ViewBag.Selecciones,"IdSeleccion","Nombre"));
        

    </div>



    <input type="submit" value="Enviar" />
}

RelacionesEntityFramework/RelacionesEntityFramework/Views/Jugador/Index.cshtml
@model List<RelacionesEntityFramework.Data.Entidades.Jugador>
@using RelacionesEntityFramework.Data.Enum;

<h2>Jugadores</h2>
<a asp-controller="Jugador" asp-action="Agregar">Agregar</a>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Fecha Nacimiento</th>
            <th>Pierna Habil</th>
            <th>Seleccion</th>

        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nombre</td>
                <td>@item.Apellido</td>
                <td>@item.FechaNacimiento</td>
                <td>@((Enums.PiernaHabil)item.PiernaHabil)</td>
                <td>@item.IdSeleccionNavigation.Nombre</td>
            </tr>
        }
    </tbody>
</table>

RelacionesEntityFramework/RelacionesEntityFramework/Views/Seleccion/Agregar.cshtml
@model RelacionesEntityFramework.Data.Entidades.Seleccion

@using (Html.BeginForm("Agregar", "Seleccion", FormMethod.Post)){ 
    @Html.LabelFor(Model=>Model.Nombre);
    @Html.EditorFor(Model=>Model.Nombre);

    @Html.LabelFor(Model => Model.Escudo);
    @Html.EditorFor(Model => Model.Escudo);

    <input type="submit" value="Enviar"/>
}

RelacionesEntityFramework/RelacionesEntityFramework/Views/Seleccion/IncorporarJugador.cshtml
<h2>Incorporar jugador a la seleccion @ViewBag.NombreSeleccion</h2>

@using (Html.BeginForm("Agregar", "Seleccion", FormMethod.Post)){
    <label>Jugador:</label>
    <select name="idJugador">
        @foreach (var j in ViewBag.Jugadores)
        {
            <option value="@j.IdJugador">@j.Apellido, @j.Nombre (@j.IdSeleccionNavigation.Nombre)</option>
        }
    </select>
    <br />
    <input type="submit" value="Enviar"/>
}

RelacionesEntityFramework/RelacionesEntityFramework/Views/Seleccion/Index.cshtml
@model List<RelacionesEntityFramework.Data.Entidades.Seleccion>


<h2>Selecciones</h2>
<a asp-controller="Seleccion" asp-action="Agregar">Agregar</a>
<table>
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Escudo</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Nombre</td>
                <td>@item.Escudo</td>
                <td>
                    <a asp-controller="Seleccion" asp-action="IncorporarJugador" 
                    asp-route-idSeleccion = "@item.IdSeleccion"> Incorporar jugador</a>
                </td>
                <td>
                    <a asp-controller="Jugador" asp-action="VerJugadorPorSeleccion"
                       asp-route-idSeleccion="@item.IdSeleccion">Ver Jugadores</a>
                </td>
            </tr>
        }
    </tbody>
</table>

RelacionesEntityFramework/RelacionesEntityFramework/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RelacionesEntityFramework</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RelacionesEntityFramework.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">RelacionesEntityFramework</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - RelacionesEntityFramework - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>