MVC-PracticaParcialUno/MVC-PracticaParcialUno/Models/CalculadoraViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace MVC_PracticaParcialUno.Models
{
    public class CalculadoraViewModel
    {
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Range(0,100,ErrorMessage ="Debe estar entre rango de 0-100")]
        public int NumeroUno { get; set; }


        [Required(ErrorMessage = "Campo Obligatorio")]
        [Range(0, 100, ErrorMessage = "Debe estar entre rango de 0-100")] 
        public int NumeroDos { get; set; }
    }
}

MVC-PracticaParcialUno/MVC-PracticaParcialUno/Models/ErrorViewModel.cs
namespace MVC_PracticaParcialUno.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MVC-PracticaParcialUno/MVC-PracticaParcialUno/Controllers/PrincipalController.cs
using Microsoft.AspNetCore.Mvc;
using MVC_PracticaParcialUno.Models;
using MVC_PracticaParcialUno.Services;
using System.Diagnostics;

namespace MVC_PracticaParcialUno.Controllers
{
    public class PrincipalController : Controller
    {
        private IPrincipalService _principalService;

        public PrincipalController(IPrincipalService principalService)
        {
            this._principalService = principalService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult CalculadoraSumar()
        {
            return View("CalculadoraSumar");
        }

        public IActionResult CalculadoraRestar()
        {
            return View();
        }


        [HttpPost]
        public IActionResult OperarSuma(CalculadoraViewModel mv) {

            if (ModelState.IsValid) {
                ViewBag.Resultado = _principalService.Sumar(mv.NumeroUno, mv.NumeroDos);
            }
            
            return View("CalculadoraSumar", mv);
        }

        [HttpPost]
        public IActionResult OperarResta(CalculadoraViewModel mv)
        {
            if (ModelState.IsValid){
                ViewBag.Resultado = _principalService.Restar(mv.NumeroUno, mv.NumeroDos);
            }

            return View("CalculadoraRestar", mv);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MVC-PracticaParcialUno/MVC-PracticaParcialUno/Views/Principal/CalculadoraRestar.cshtml
@model MVC_PracticaParcialUno.Models.CalculadoraViewModel

<div class="d-flex justify-content-center">
    <form asp-controller="Principal" asp-action="OperarResta" class="w-50 border-1 border box-shadow p-4 d-flex flex-column gap-2" method="post">
        <h1 class="fw-lighter">Calculadora de restas</h1>
        <div>
            <div class="d-flex flex-row gap-4">
                <label class="w-25">Numero Uno</label>
                <input type="number" asp-for="NumeroUno" placeholder="Numero 1" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="NumeroUno"></span>
        </div>

        <div>
            <div class="d-flex flex-row gap-4">
                <label class="w-25">Numero Dos</label>
                <input type="number" asp-for="NumeroDos" placeholder="Numero 2" class="form-control" />
            </div>
            <span class="text-danger" asp-validation-for="NumeroDos"></span>
        </div>

        <button type="submit" class="btn btn-success text-white text-center py-2">Operar</button>

        @if (ViewBag.Resultado != null)
        {
            <h4 class="text-success fw-bold text-center my-4">@ViewBag.Resultado</h4>
        }
    </form>


</div>

MVC-PracticaParcialUno/MVC-PracticaParcialUno/Views/Principal/CalculadoraSumar.cshtml
@model MVC_PracticaParcialUno.Models.CalculadoraViewModel

<div class="d-flex justify-content-center">
    <form asp-controller="Principal" asp-action="OperarSuma" class="w-50 border-1 border box-shadow p-4 d-flex flex-column gap-2" method="post">
        <h1 class="fw-lighter">Calculadora de sumas</h1>
        <div>
            <div class="d-flex flex-row gap-4">
                <label class="w-25">Numero Uno</label>
                <input type="number" asp-for="NumeroUno" placeholder="Numero 1" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="NumeroUno"></span>
        </div>
        
        <div>
            <div class="d-flex flex-row gap-4">
                <label class="w-25">Numero Dos</label>
                <input type="number" asp-for="NumeroDos" placeholder="Numero 2" class="form-control"/>
            </div>
            <span class="text-danger" asp-validation-for="NumeroDos"></span>
        </div>
        
        <button type="submit" class="btn btn-success text-white text-center py-2">Operar</button>

        @if (ViewBag.Resultado != null)
        {
            <h4 class="text-success fw-bold text-center my-4">@ViewBag.Resultado</h4>
        }
    </form>


</div>

MVC-PracticaParcialUno/MVC-PracticaParcialUno/Views/Principal/Index.cshtml
<h1 class="fs-1 text-center fw-light">Bienvenido al sitio de evaluacion</h1>

<div class="d-flex flex-column align-items-center gap-3 mt-4">
    <a asp-controller="Principal" asp-action="CalculadoraSumar" class="fs-4 fw-semibold btn btn-success text-white text-decoration-none">Ir a Calculadora de Sumas</a>
    <a asp-controller="Principal" asp-action="CalculadoraRestar" class="fs-4 fw-semibold btn btn-success text-white text-decoration-none">Ir a Calculadora de Restas</a>
</div>